// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWKB6XEd6MzAd9PNew1VRnTRBmDR642TU',
    appId: '1:289796607424:android:19517e27dbecf8a066cc25',
    messagingSenderId: '289796607424',
    projectId: 'roundapp-a671d',
    storageBucket: 'roundapp-a671d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp4h4RdsdzhFvgjEiN3BVKVwQZKRNvAtE',
    appId: '1:289796607424:ios:4943b0014fd689dd66cc25',
    messagingSenderId: '289796607424',
    projectId: 'roundapp-a671d',
    storageBucket: 'roundapp-a671d.appspot.com',
    androidClientId: '289796607424-k1k8j5m7088g9ute556h23adn78agkjo.apps.googleusercontent.com',
    iosClientId: '289796607424-ubjtqf34rsjoijmel9t6s91ffcqn1vkq.apps.googleusercontent.com',
    iosBundleId: 'com.round.app',
  );
}
