// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM5BBLFLeqyqS3TziaZVg7iBL50jUx1Vo',
    appId: '1:656049603780:android:d91e3aa41ade63f57b3591',
    messagingSenderId: '656049603780',
    projectId: 'round-app-63f07',
    databaseURL: 'https://round-app-63f07-default-rtdb.firebaseio.com',
    storageBucket: 'round-app-63f07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcYoo5G8xOxECz34bx8WDynjlxAowo_-Q',
    appId: '1:656049603780:ios:91d429693365f2f07b3591',
    messagingSenderId: '656049603780',
    projectId: 'round-app-63f07',
    databaseURL: 'https://round-app-63f07-default-rtdb.firebaseio.com',
    storageBucket: 'round-app-63f07.appspot.com',
    iosClientId: '656049603780-on71cc65qftaf3dtelbdhv4b9b8fc28r.apps.googleusercontent.com',
    iosBundleId: 'com.round.app',
  );
}
